id = "rust-rover-dark-theme"
name = "RustRover Dark Theme"
version = "1.0.1"
schema_version = "2"
authors = ["Islam Bekbuzarov <blkmlkss@gmail.com>"]
description = "A dark theme inspired by RustRover's default dark theme"
repository = "https://github.com/blkmlk/RustRover-Zed-Theme"
